#!/bin/sh
# postinst script for graylog2-server
#
# Author: Claudio Filho <claudio.filho@locaweb.com.br>

set -e

APP_PATH="/var/www/graylog2-web"

case "$1" in
    configure|reconfigure)
        if ! getent group graylog2 2> /dev/null; then
            addgroup --quiet --system graylog2
        fi
        if ! getent passwd graylog2 2> /dev/null; then
            adduser --quiet --system --no-create-home --disabled-password --gid $(getent group graylog2 | cut -d: -f3) --home ${APP_PATH} graylog2
        fi
        chmod +x /etc/init.d/graylog2-server
        update-rc.d -f graylog2-server defaults >/dev/null
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
